# Small model KTO train config.
#
# Usage:
#   oumi train -c configs/recipes/phi3/kto/train_small.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/train/train.html
#   - Config class: oumi.core.configs.TrainingConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/training_config.py
#   - Other training configs: configs/**/pretraining/, configs/**/sft/, configs/**/dpo/

model:
  model_name: "gpt2"  # Small 124M param model
  trust_remote_code: True

data:
  train:
    datasets:
      - dataset_name: "trl-lib/kto-mix-14k"

training:
  optimizer: "adamw_torch"
  use_peft: true
  output_dir: "output/gpt2.kto"
  trainer_type: "TRL_KTO"
  num_train_epochs: 1
  max_steps: 20
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4

peft:
  q_lora: False
  lora_target_modules:
    - "c_attn"
    - "c_proj"
    - "c_fc"
    - "attn.c_proj"
