# Copyright 2025 - Oumi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Basic JAX inference config for Llama 3 8B.
#
# ⚠️ Experimental: JAX backend is under active development
#
# Requirements:
#   - Install JAX dependencies: `pip install oumi[jax]`
#   - Log into HF: `huggingface-cli login`
#   - Request access to Llama 3.1: https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct
#
# Usage:
#   oumi infer -i -c configs/examples/jax_inference/llama3_basic.yaml
#
# See Also:
#   - JAX Integration Docs: docs/jax_integration.md
#   - JAX LLM Examples: https://github.com/jax-ml/jax-llm-examples
#   - JAX Scaling Guide: https://jax-ml.github.io/scaling-book/
#   - Config class: oumi.core.configs.InferenceConfig

model:
  model_name: "meta-llama/Llama-3.1-8B-Instruct"
  model_max_length: 4096
  torch_dtype_str: "bfloat16"
  load_pretrained_weights: true
  trust_remote_code: true

generation:
  max_new_tokens: 512
  temperature: 0.7
  top_p: 0.9
  do_sample: true

# Use JAX inference engine for high-performance inference
engine: JAX

# JAX-specific optimizations
jax_config:
  # Enable XLA compilation for optimized kernels
  enable_xla: true

  # Memory management
  memory_fraction: 0.9

  # Use JAX's native attention kernels
  use_flash_attention: true

  # Quantization (optional - reduces memory usage)
  # quantization: "int8"
