# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
    files: \.(py|md)$
  - id: trailing-whitespace
    files: \.(py|md|ipynb)$
  - id: debug-statements
    files: \.py$  # only include python files
  - id: mixed-line-ending  # remove CR
    args: [--fix=lf]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.10
  hooks:
  - id: ruff
